### ISSUE TITLE
Cannot enable wifi

### ISSUE THREAD

**Issue by GrayJack** [GhostBSD/networkmgr#6]
I'm using freeBSD 11.1, and networkmgr 2.2
When I click on Enable Wifi, nothing happens, I'm sure, and networkmgr are sute that wifi card is setup just right.

So, what info you guys need to know what's the cause of the problem?

**Comment by ericbsd** [comment]
Did you setup doas?

On Aug 7, 2017 05:28, "GrayJack" <notifications@github.com> wrote:

I'm using freeBSD 11.1
When I click on Enable Wifi, nothing happens, I'm sure, and networkmgr are
sute that wifi card is setup just right.

So, what info you guys need to know what's the cause of the problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GhostBSD/networkmgr/issues/6>, or mute the thread

**Comment by GrayJack** [comment]
Yes, I did

**Comment by ericbsd** [comment]
Are you using ligtbm?

There is a problem that i try to figure out causing by Lightdm.

On Aug 7, 2017 06:24, "GrayJack" <notifications@github.com> wrote:

Yes, I did

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/GhostBSD/networkmgr/issues/6#issuecomment-320614988>,
or mute the thread

**Comment by GrayJack** [comment]
I'm using SLiM

**Comment by asxbsd** [comment]
what wifi adapater ?

**Comment by GrayJack** [comment]
The bwn one, I f I remember it correctly it's the Broadcom 43XX

**Comment by asxbsd** [comment]
that will need firmware built from ports, not available as a pkg.
Please post on forums.ghostbsd.org or join #ghostbsd on freenode for further help.

**Comment by ericbsd** [comment]
OK can you give me the out put of the commant networkmgr, ifconfig and cat
rc.conf.

**Comment by GrayJack** [comment]
networkmgr:
`Your wired network card is already configured.
Your wifi network card is already configured.
`
ifconfig
`bge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8009b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,LINKSTATE>
	ether 00:26:22:cf:31:eb
	hwaddr 00:26:22:cf:31:eb
	inet 192.168.1.36 netmask 0xffffff00 broadcast 192.168.1.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
wlan0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 0c:60:76:9a:0a:b0
	hwaddr 0c:60:76:9a:0a:b0
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: IEEE 802.11 Wireless Ethernet autoselect (autoselect)
	status: no carrier
	ssid "" channel 165 (5825 MHz 11a)
	regdomain FCC country US authmode WPA1+WPA2/802.11i privacy MIXED
	deftxkey UNDEF txpower 23 bmiss 7 mcastrate 6 mgmtrate 6 scanvalid 60
	wme roaming MANUAL bintval 0
	groups: wlan 
`
cat rc.conf
`hostname="FreeBSD"
keymap="br275.iso.acc.kbd"
# Wired network
ifconfig_bge0="DHCP"
# Wireless network
wlans_bwn0="wlan0"
ifconfig_wlan0="WPA DHCP"

# Others
local_unbound_enable="YES"
sshd_enable="YES"
moused_enable="YES"
powerd_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
dbus_enable="YES"
hald_enable="YES"
slim_enable="YES"
`

**Comment by asxbsd** [comment]
it turned out to be a firmware iissue.
